### ISSUE TITLE
Box86 + Box64 in Winlator Glibc

### ISSUE THREAD

**Issue by alexvorxx** [longjunyu2/winlator#156]
Hi.
Is it possible to make Winlator Glibc Native with Box86 + Box64 + Wine (non-WoW64) ?
Box64 + Wine (WoW64) has the worst performance in OpenGL games.

**Comment by shishiwow** [comment]
Box86 has been abandoned by various developers. You can look forward to wow64de optimization, but don't think about Box86 anymore.

**Comment by lvonasek** [comment]
No plans to support Box86.

**Comment by dave9292** [comment]
@Ivonasek
I would not write off box86, unlike Box64, which is being actively developed, Box86 has essentially been completed for a long time and serves as an excellent launcher for old games, even Box32 cannot replace Box86, since all instructions are executed in the x64 environment, which breaks many games and has lower fps.
