### ISSUE TITLE
[Feature Request] Block internet access for certain games

### ISSUE THREAD

**Issue by Lyzing** [longjunyu2/winlator#182]
With Steam still not running properly many of us use cracks to get certain games to run and while I have no fear about viruses since it runs sandboxed I would still feel better if I could block internet access when ever I run such games

**Comment by lvonasek** [comment]
Due to legal reasons we will not support using cracks in any way (although people might have a legal copy of a game and use a crack just for compatibility).

You can always disable the app internet permission in the system settings (if your Android version supports it) or disable WiFi and mobile data.
