### ISSUE TITLE
[Enhance] Reduce dinput trigger value to adapt to uncalibrated trigger button

### ISSUE THREAD

**Issue by ProDanTe69** [longjunyu2/winlator#33]
L2 R2 button not working in both wine

**Comment by longjunyu2** [comment]
Have you tried `Settings` -> `Trigger Mode` -> `As Button` or `As Axis` ?

**Comment by ProDanTe69** [comment]
Yes but not working

**Comment by longjunyu2** [comment]
@ProDanTe69 what is the device name showed in `Wine Game Controller` dialog? And does xinput works in 9.15 when you set `Trigger Mode` to `As Axis`?

**Comment by longjunyu2** [comment]
I guess the controller you are using needs to be calibrated because its trigger button cannot reach its maximum value. However, I will also make some improvements on the software side to alleviate this issue, as most controllers may experience misalignment.

**Comment by ProDanTe69** [comment]
Yes only xinput but dinput not responding

**Comment by longjunyu2** [comment]
Implemented linear triggers in DInput, which also resolves this issue.

**Comment by Dragon-11976** [comment]
@longjunyu2 There is a problem in the game Dragon's Dogma when I run the game on the Xinput controller, the game runs on two controllers at the same time, it runs on the Virtual Gamepad and the Xbox Controller, and also the buttons are inverted in the game only. This is the problem I faced in the game
Also I tried As Button or As Axis same problem
![Screenshot_2024-08-21-17-15-04-623_com miui gallery-edit](https://github.com/user-attachments/assets/005386b5-2ce1-4453-970c-eee535548c67)
Also the L3 and R3 buttons are reversed and their function is not present as if they are copied

**Comment by Dragon-11976** [comment]
Uploading (1) Screenrecorder-2024-08-21-17-07-45-410.mp4…

**Comment by Dragon-11976** [comment]
Uploading (1) Screenrecorder-2024-08-21-17-07-45-410.mp4…

**Comment by longjunyu2** [comment]
@Dragon-11976 It means that you played this game with xbox controller and virtual controller at the same time?

**Comment by Dragon-11976** [comment]
> @Dragon-11976هل هذا يعني أنك لعبت هذه اللعبة باستخدام وحدة تحكم Xbox ووحدة التحكم الافتراضية في نفس الوقت؟

No, the game is played alone with two controllers at the same time.

**Comment by Dragon-11976** [comment]
> @Dragon-11976 It means that you played this game with xbox controller and virtual controller at the same time?

I want to send you a video so you can understand this issue but this video never wants to be sent in github here

**Comment by Dragon-11976** [comment]
@longjunyu2 I sent you a video in gmail for you to check out.

**Comment by longjunyu2** [comment]
@Dragon-11976 sorry, I don't receive any email in my gmail... Would you like to send again? To 877730493@qq.com

**Comment by Dragon-11976** [comment]
> @Dragon-11976عذرا، لا أتلقى أي بريد إلكتروني في gmail الخاص بي... هل ترغب في الإرسال مرة أخرى؟ إلى [877730493@qq.com](mailto:877730493@qq.com)

Ok I will send it to you shortly thank you for your interest 😁

**Comment by Dragon-11976** [comment]
> @Dragon-11976عذرا، لا أتلقى أي بريد الكتروني في gmail الخاص بي... هل ترغب في إرسال المزيد مرة أخرى؟ إلى [877730493@qq.com](mailto:877730493@qq.com)

I sent it to you, you will see some times when I move using a joystick, you will see that the Virtual Gamepad control is the one that works only when I move the camera, especially for the game, it works with the Xbox Controller, and also the R3 and L3 buttons have special features that do not exist because the buttons are inverted, and also some buttons are missing because two controls are running at the same time 😁
![Uploading Screenshot_2024-08-22-16-26-02-081_com.google.android.gm.jpg…]()

**Comment by Dragon-11976** [comment]
> > @Dragon-11976عذرا، لا أتلقى أي بريد الكتروني في gmail الخاص بي... هل ترغب في إرسال المزيد مرة أخرى؟ إلى [877730493@qq.com](mailto:877730493@qq.com)
> 
> I sent it to you, you will see some times when I move using a joystick, you will see that the Virtual Gamepad control is the one that works only when I move the camera, especially for the game, it works with the Xbox Controller, and also the R3 and L3 buttons have special features that do not exist because the buttons are inverted, and also some buttons are missing because two controls are running at the same time 😁

![Uploading Screenshot_2024-08-22-16-26-02-081_com.google.android.gm.jpg…]()

**Comment by longjunyu2** [comment]
@Dragon-11976  ok, I think I understand what happened. For now, winlator just support one controller at same time.
So use virtual controller or your xbox 360 controller, but don't use them together.

Generally speaking, multi controller support involves mapping multiple controllers one by one, rather than mapping two controllers into one. Therefore, your problem may not be resolved. But you can use key mapping to complete some operations instead of virtual controllers.

**Comment by Dragon-11976** [comment]
> @Dragon-11976 حسنًا، أعتقد أنني فهمت ما حدث. في الوقت الحالي، يدعم برنامج Winlator وحدة تحكم واحدة فقط في نفس الوقت. لذا، استخدم وحدة التحكم الافتراضية أو وحدة تحكم Xbox 360، ولكن لا تستخدمهما معًا.
> 
> بشكل عام، يتضمن دعم وحدات التحكم المتعددة تعيين وحدات تحكم متعددة واحدة تلو الأخرى، بدلاً من تعيين وحدتي تحكم في وحدة واحدة. لذلك، قد لا يتم حل مشكلتك. ولكن يمكنك استخدام تعيين المفاتيح لإكمال بعض العمليات بدلاً من وحدات التحكم الافتراضية.

Well thank you very much brother 😁

**Comment by Dragon-11976** [comment]
@longjunyu2 Thank you for this new update, frankly, all the problems that were in 7.1.2 have been fixed.

Also, the Dragon's dogma game has fixed the problem that I told you about. Thank you. Now the game works with xinput in an amazing way and all the buttons are working and there is no inverted button. The game now works with one controller for me, Xbox 360. Thank you, legend.
![Screenshot_2024-08-29-19-49-09-113_com winlator](https://github.com/user-attachments/assets/d8122732-c318-4d70-af92-d7276cfb233a)

Also, in this new update, finally, the game sekiro has been supported on xinput. I did not expect this. Thank you very much.
![Screenshot_2024-08-30-01-26-51-806_com winlator](https://github.com/user-attachments/assets/6dbabccc-777f-4e0e-8159-5fdb2cd21596)
Only in the game THYMESIA, it is not supported on xinput. When I try it on Dinput, only one button works, it is my analogue. Move in the game, but the camera and all the other buttons do not work at all. Another immersion. Thank you for this update. It has fixed many amazing things. See you later
![Screenshot_2024-08-30-03-59-06-207_com winlator](https://github.com/user-attachments/assets/5e43a550-488f-4b64-8f67-60513a2cf72c)
![Screenshot_2024-08-30-04-06-24-064_com winlator](https://github.com/user-attachments/assets/4075c388-0688-47c2-89a6-9889ea584d75)

**Comment by Dragon-11976** [comment]
@longjunyu2 
![Screenshot_2024-08-30-03-49-52-080_com winlator](https://github.com/user-attachments/assets/2dade401-2be5-4e25-883d-82edc8a4ded3)
![Screenshot_2024-08-30-03-53-01-103_com winlator](https://github.com/user-attachments/assets/80d7f50c-cda6-4e90-8040-3ba7e5db3070)
![Screenshot_2024-08-30-03-53-15-143_com winlator](https://github.com/user-attachments/assets/e2432420-d3b5-4bfe-a7d0-2fd3b013e26d)
![Screenshot_2024-08-30-03-53-24-004_com winlator](https://github.com/user-attachments/assets/9ed6406f-4911-4628-a204-6854c6c74140)
![Screenshot_2024-08-30-19-59-39-854_com miui gallery-edit](https://github.com/user-attachments/assets/8e62297f-22c7-4574-8946-b0399559133b)

There is also a problem with the Greed Fall game, where when I run the game in performance mode, a message appears that says “error” for my memory. This message appears in the original version 7.1. Also, this problem only appears in performance mode. As for Compatibility mode, the game works well without any message appearing at all. I tried everything with this problem and all methods did not work. The game is not supported in performance mode, unfortunately. I hope that this problem will be fixed in future updates. Thank you for this wonderful update 🫡
