### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by lvonasek** [longjunyu2/winlator#96]
In the last weeks this is the most active Winlator fork. I noticed several forks steal from this repository and release an APK without sharing the source code. After checking their repositories, I see their own changes are minimal and they are just getting credit for work of others.

As their repositories are not opensource, there is no easy way to validate they didn't add any virus or malware into the app.

Due to this I want to change the license to GPL3/MIT. GPL3 will cover the changes in this fork and MIT will cover the code from Bruno. That will force other forks to release their source code when using our work.

**Comment by longjunyu2** [comment]
I agree with you, and after changing the license, we need to do more work to achieve the goals.


I have browsed several related repositories, and most of the changes they made were related to compressed files in assets. In fact, what we provide in this regard is also packaged files, so we need a repository to provide build methods (patches and scripts) for imagefs and other packages. So we can change the license first and create a repository about imagefs in the future.


And I had some ideas about refactoring code. The current code is not easy to maintain, what do you think about this?



---Original---
From: "Luboš ***@***.***&gt;
Date: Thu, Sep 5, 2024 13:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [longjunyu2/winlator] Change license (Issue #96)




 
In the last weeks this is the most active Winlator fork. I noticed several forks steal from this repository and release an APK without sharing the source code. After checking their repositories, I see their own changes are minimal and they are just getting credit for work of others.
 
As their repositories are not opensource, there is no easy way to validate they didn't add any virus or malware into the app.
 
Due to this I want to change the license to GPL3/MIT. GPL3 will cover the changes in this fork and MIT will cover the code from Bruno. That will force other forks to release their source code when using our work.

**Comment by lvonasek** [comment]
No need to sorry @OceanSea1. I am thankful that you take your time to help the users with their reported issues.

About the mainpage: I do not have myself much overview on what hardware it works and on what HW it doesn't. Feel free to create a pull request modifying the main page.

One suggestion from my side would be to explain to the users that it is much easier to fix an issue if they provide logs. Most games are failing because there is missing some DLL or framework (which is visible in the log).

**Comment by lvonasek** [comment]
@longjunyu2, could you release 7.1.4 from the current main branch? I do not have any fixes coming soon and I think some the fixes are worth releasing.

**Comment by Kingbb1** [comment]
Hi Thanks For that's great work guys I appreciate ❤️
@lvonasek  I have a question
Well, wouldn't it be better to release it after it is merged with the source code, followed Bruno? The problem is that there is no application to communicate with it or anything 🙂 So far the source code has not been released and I heard news that Bruno does not want to release the source code. Is this true and why doesn't he want it?

**Comment by lvonasek** [comment]
We can release an update once it is merged with Bruno's source code (although I would be careful as some users reported performance decrease with his latest build).

I would be happy to contribute directly into Bruno's fork but he refused it. It is hard to maintain my fixes if he doesn't communicate and it takes months to him to merge it.

He did a great job in Winlator but he failed in building opensource community, which now ended with a big Winlator fragmentation.

Bruno has evidently a problem with all the Winlator mods and forks. That's why he's not updating the source codes.

**Comment by Kingbb1** [comment]
@lvonasek 
And if he didn't want anyone's help to develop the emulator, he would have saved a lot of time, as I mentioned.Also this is the reason behind many edits because he doesn't want to help anyway. Thank you to you and everyone who contributed to the project. I appreciate your effort very much. It's exhausting and takes time. So thank you all take your rest and I hope I can support you more ❤️

**Comment by longjunyu2** [comment]
@lvonasek Alright. Before the new release, let me finish the new MIDI function. 
My progress over the past two months has been very slow, but I will have more time to dedicate to this project next year.

**Comment by lvonasek** [comment]
Perfect, thank you
